name: Email Processor

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  process-emails:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run email processor
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DAYS_THRESHOLD: ${{ secrets.DAYS_THRESHOLD }}
        ALLOWED_DOMAINS: ${{ secrets.ALLOWED_DOMAINS }}
      run: |
        python outlook_openai_integration.py 